[package]
name = "autoclear-bot"
version = "0.1.0"
authors = ["jude-LafiteIII <judewrs@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.9.0"
typemap = "0.3.3"
mysql = "14.2.0"
serenity = "0.7.4"
