CREATE TABLE autoclear.channels (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    channel BIGINT UNSIGNED NOT NULL,
    user BIGINT UNSIGNED DEFAULT NULL,
    timeout INT UNSIGNED NOT NULL DEFAULT 10,
    message TEXT,

    PRIMARY KEY (id)
);

CREATE TABLE autoclear.deletes (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    channel BIGINT UNSIGNED NOT NULL,
    message BIGINT UNSIGNED NOT NULL,
    `time` DATETIME NOT NULL,

    PRIMARY KEY (id)
);
